# docker compose의 version
# docker compose의 기능에 영향을 미친다
version: "3.8"
services:
  # 기본적으로 docker-compose의 service는 --rm -d 가 기본 설정으로 붙는다
  # docker가 이름을 기억하지만, 컨테이너 이름은 다른 것이된다
  # 코드내에서는 올바르게 들어가서 걱정 할 필요 없다
  mongodb:
    # 사용하려는 이미지 이름
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
      # 2가지 모두 가능
      # MONGO_INITDB_ROOT_USERNAME: max
      # MONGO_INITDB_ROOT_PASSWORD: secret
      # - MONGO_INITDB_ROOT_USERNAME=max
    # 파일 사용
    env_file:
      - ./env/mongo.env
    # 없다면, 도커가 생성하는 기본 네트워크에 소속된다
    # networks:
    #   - goals-net
  backend:
    # Dockerfile의 경로
    # build: ./backend
    # 같은 동작을 한다, 세부 설정 가능
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # args 삽입 가능
    # args: something
    #  some-arg: value
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs 
      # 바인딩 마운트, docker-compose의 위치로 사용 가능, 데스크톱 환경 비활성
      #- ./backend:/app
      # - /app/node_modules 
    env_file:
      - ./env/backend.env
    # docker-compose에만 있는 명령
    # 의존성이 있는 컨테이너(순서 정하기)
    # 백엔드는 db가 실행 된 후 실행되어야 하기 때문
    depends_on:
      - mongodb
  frontend:
    # 이미지가 변경되지 않는다면 그대로 사용, 변경된다면 재 빌드
    build: ./frontend
    ports:
      - '3000:3000'
    # 바인딩 마운트
    # volumes:
    #   - ./frontend/src:/app/src
    # -it flag는 개방향 표준 입력을 위한 -와 입력 플래그의 조합
    # 해당 2옵션은 -it와 같은 효과가 있다
    stdin_open: true
    tty: true
    # 의존성 설정
    # 백엔드가 먼저 실행되어야 한다
    depends_on:
      - backend
# 명명된 볼륨을 위해 반드시 필요하다
volumes:
  data:
  logs: